<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MENAMPILKAN KOTAK</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<?php $_A = "A";
      $_B = "B";
      $_C = "C";
?>

    <!-- <div class="container"> -->
        <div class="kotak1">
            <?php echo $_A; ?>
        </div>
        <div class="kotak1">
            <?php echo $_A; ?>
        </div>
        <div class="kotak1">
            <?php echo $_A; ?>
        </div>
        <div class="kotak2">
            <?php echo $_B; ?>
        </div>
        <div class="kotakB">
            <?php echo $_B; ?>
        </div>
        <div class="kotak3">
            <?php echo $_C; ?>
        </div>
    <!-- </div> -->
</body>
</html>